In [1]:
import numpy as np



THE BASICS

In [2]:
a=np.array([22,2,3,4])


In [3]:
print(a)

[22  2  3  4]


In [5]:
b=np.array([[1,2,4],[2,3,5]])


In [6]:
a.ndim # get dimension

1

In [7]:
b.ndim

2

In [8]:
# get shape
a.shape

(4,)

In [9]:
b.shape

(2, 3)

In [11]:
# get type (how much memory our array is taking )
a.dtype

dtype('int32')

In [12]:
b.dtype

dtype('int32')

In [13]:
# get size (it gives the byte size)
a.itemsize

4

In [14]:
b.itemsize

4

In [16]:
c=np.array([2,3,4],dtype="int16")


In [17]:
print(c)

[2 3 4]


In [19]:
c.dtype

dtype('int16')

In [20]:
c.itemsize

2

In [23]:
a.itemsize

4

In [22]:
# Get the total size
c.size*c.itemsize


6

In [27]:

# or another way to do the same thing
c.nbytes

6

In [25]:
a.size*a.itemsize

16

### Accessing/Changing specific elements, rows, columns,etc

In [29]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]],dtype="int16")


In [30]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [31]:
a.shape

(2, 7)

In [32]:
# to get a specific element [r,c]
a[1,3]


11

In [33]:
a[1,-2]

13

In [34]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7], dtype=int16)

In [35]:
# to get a specific column
a[:,2]

array([ 3, 10], dtype=int16)

In [36]:
# get a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6], dtype=int16)

In [37]:
# we can do same with negative indexing
a[0,1:-1:2]

array([2, 4, 6], dtype=int16)

In [39]:
a[1,3:6:2]

array([11, 13], dtype=int16)

In [40]:
# to change a specific element
a[1,5]=21

In [41]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 21 14]]


In [42]:
# to change an entire column
a[:,2]=5

In [43]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 21 14]]


In [44]:
a[:,3]=[2,3]

In [45]:
print(a)

[[ 1  2  5  2  5  6  7]
 [ 8  9  5  3 12 21 14]]


In [46]:
a[1,:3]=6
print(a)

[[ 1  2  5  2  5  6  7]
 [ 6  6  6  3 12 21 14]]


In [49]:
# 3 dimention example
d=np.array([[[1,2],[2,3],[3,4],[5,6]]])
print(d)

[[[1 2]
  [2 3]
  [3 4]
  [5 6]]]


In [50]:
print(d.ndim)

3


In [51]:
d.shape # here 1 is one entire block 4 is 4 rows asd 2 is columns

(1, 4, 2)

In [52]:
d=np.array([[[1,2],[2,3]],[[3,4],[5,6]]])
print(d)

[[[1 2]
  [2 3]]

 [[3 4]
  [5 6]]]


In [53]:
print(d.ndim)

3


In [54]:
d.shape

(2, 2, 2)

In [55]:
# to get a specify element (worl outside in)
# here with d to get element 3
print(d[0,1,1])


3


In [56]:
# to get 5 element 
print(d[1,1,0])

5


In [57]:
d[:,1,:] # its 1 row from noth block

array([[2, 3],
       [5, 6]])

In [58]:
d[:,:,1]

array([[2, 3],
       [4, 6]])

In [59]:
# to replace
d[:,:,1]=[[5,5],[6,6]]

In [60]:
print(d)

[[[1 5]
  [2 5]]

 [[3 6]
  [5 6]]]


### Initializing different types of arrays

In [61]:
# all 0s matrix
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [63]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [65]:
# All 1s matrix
np.ones((3))

array([1., 1., 1.])

In [66]:
np.ones((2,3),dtype="int16")

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [67]:
np.ones(((2,2,3)))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [68]:
# Any Other number
np.full((2,3),5)  # in this first define shape and than value

array([[5, 5, 5],
       [5, 5, 5]])

In [69]:
np.full((3,2),6,dtype="float16")

array([[6., 6.],
       [6., 6.],
       [6., 6.]], dtype=float16)

In [70]:
# any other number(full_like)
np.full_like(a,4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]], dtype=int16)

In [71]:
a=np.ones((2,3))

In [72]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [73]:
np.full_like(a,4)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [74]:
# random decimal numbers
np.random.rand(2,3)


array([[0.24465735, 0.52529774, 0.77550344],
       [0.19978854, 0.87797849, 0.58266836]])

In [75]:
np.random.random_sample(a.shape)

array([[0.5202482 , 0.74626036, 0.14389787],
       [0.23010411, 0.68446252, 0.91258565]])

In [78]:
# arndom Integers Values
np.random.randint(7,size=(3,3))  # from this you can find a matrix of size 3x3 with numbers b/w 0 to 6

array([[5, 0, 0],
       [3, 3, 0],
       [1, 1, 1]])

In [80]:
np.random.randint(4,9,size=(3,2))  # you can find different matrix each time you run

array([[4, 4],
       [7, 4],
       [6, 8]])

In [81]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [83]:
# Repeat an array
arry=np.array([[1,2,3]])
a1=np.repeat(arry,2,axis=0)
print(a1)

[[1 2 3]
 [1 2 3]]


In [84]:
arry=np.array([[1,2,3]])
a1=np.repeat(arry,3,axis=1)
print(a1)

[[1 1 1 2 2 2 3 3 3]]


In [86]:
 #create array 
arry1=np.ones((5,5))
print(arry1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [88]:
# now replace inner matrix to zeros
z=np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [89]:
# now replace 0 with 9
z[1,1]=9

In [90]:
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [92]:
# now put z inside arry1
arry1[1:4,1:4]=z
print(arry1)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be carefull when copying an array

In [93]:
a=np.array([1,2,3])
print(a)
b=a

[1 2 3]


In [94]:
print(b)

[1 2 3]


In [95]:
b[0]=100
print(b)

[100   2   3]


In [96]:
print(a) # as we make a copy of a directly both a and the b poiying ot the same memory location so chaging anything in b will going to change the same in a

[100   2   3]


In [97]:
# rigjt method to copy an array
a=np.array([4,5,6])
b=a.copy()

In [98]:
print(b)

[4 5 6]


In [99]:
b[1]=10
print(b)


[ 4 10  6]


In [100]:
print(a)

[4 5 6]


In [17]:
## We can index with a list in numpy
a=np.array([1,23,4,5,6,7,8,9])
a[[1,2,7]]

array([23,  4,  9])

#### Mathematics


In [106]:
# element wise addition,subtraction,multiplication etc
a=np.array([1,2,3,4])
print(a)
print()
print(a+2)
print()
print(a-1)
print()
print(a*4)
print()
print(a/2)
print()
print(a**2)


[1 2 3 4]

[3 4 5 6]

[0 1 2 3]

[ 4  8 12 16]

[0.5 1.  1.5 2. ]

[ 1  4  9 16]


In [107]:
a+=2
print(a)

[3 4 5 6]


In [113]:
b=np.array([1,0,1,0])
print(a)
print()
print(b)
print()
print(a+b)

[ 0.14065208 -0.68660026 -0.81857414 -0.27579386]

[1 0 1 0]

[ 1.14065208 -0.68660026  0.18142586 -0.27579386]


In [112]:
a=np.sin(a)
print(a)

[ 0.14065208 -0.68660026 -0.81857414 -0.27579386]


In [114]:
b=np.tan(a)
print(b)

[ 0.14158698 -0.8196365  -1.06865484 -0.28300587]


##### Linear Algebra

In [119]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [122]:
c=np.matmul(a,b)
print(c)

[[6. 6.]
 [6. 6.]]


In [124]:
# find the determinant
d=np.identity(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [125]:
np.linalg.det(d)

1.0

#### Statistics

In [128]:
stats=np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [136]:
np.min(stats)


1

In [130]:
np.max(stats)

6

In [132]:
np.min(stats,axis=0) # row wise

array([1, 2, 3])

In [133]:
np.min(stats,axis=1) # column wise

array([1, 4])

In [134]:
np.max(stats,axis=0)

array([4, 5, 6])

In [135]:
np.max(stats,axis=1)

array([3, 6])

#### Reorganizing Array

In [138]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)


[[1 2 3 4]
 [5 6 7 8]]


In [140]:
b=a.reshape((4,2))
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [141]:
b=a.reshape((2,2,2))
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [142]:
b=a.reshape((8,1))
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


note reshape will wrok only when we provide the correct size (row*column should be equal to no of element)

In [143]:
b=a.reshape((3,2))

ValueError: cannot reshape array of size 8 into shape (3,2)

In [144]:
# Vertically stacking vectors

In [146]:
v1=np.array([1,2,3,4])  # no of columns should be same
v2=np.array([5,6,7,8])
np.vstack((v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [147]:
np.vstack((v1,v2,v2,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [162]:
np.vstack((v1,v2,v2,v1))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [ ]:
# horizonatal stack

In [152]:
v3=np.zeros((2,3)) # in this row should be same
print(v3)


[[0. 0. 0.]
 [0. 0. 0.]]


In [157]:
v4=np.ones((2,2))
print(v4)

[[1. 1.]
 [1. 1.]]


In [158]:
np.hstack((v3,v4))

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

#### MIscellaneous

###### Load data from File

In [12]:
filedata=np.genfromtxt("data.txt",delimiter=",")
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,   1.,   2.,  33., 766.,  75.,   4.,  55.,   6.,   4.,
          3.,   4.,   5.,   6.,   7.,   0.,  11.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  68.]])

now as we can see this is a float data and if we want to change the datatype of this we can do that with 

In [13]:
filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,   1,   2,  33, 766,  75,   4,  55,   6,   4,   3,   4,
          5,   6,   7,   0,  11],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  68]])

##### Boolean Masking And Advanced Indexing

In [18]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [19]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  68])

In [20]:
filedata.ndim

2

In [21]:
np.any(filedata>50,axis=0) # go downwords if any of column have value greater than  it will be true otherwise it will be false

array([False, False, False, False,  True,  True,  True, False,  True,
       False, False, False, False, False, False, False,  True,  True])

In [23]:
np.all(filedata>50,axis=1)

array([False, False, False])

In [24]:
np.all(filedata>50,axis=0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [27]:
((filedata>50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False,  True, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [26]:
(~(filedata>50)& (filedata<100))

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False, False,  True, False,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [ ]:
a=np.array([[1,2,3,4]])